import { PrismaClient, BackgroundType, CardStyle, DateDisplayStyle } from "@prisma/client";

const prisma = new PrismaClient();

const systemTemplates = [
  {
    name: "קלאסי לבן",
    description: "עיצוב נקי וקלאסי עם רקע לבן",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.COLOR,
    backgroundColor: "#ffffff",
    cardStyle: CardStyle.ELEVATED,
    cardBackground: "#ffffff",
    cardBorderRadius: 16,
    cardPadding: 24,
    cardMaxWidth: 448,
    textColor: "#1a1a1a",
    primaryColor: "#1a1a1a",
    accentColor: "#1a1a1a",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showTimeSection: true,
    showAddressSection: true,
    showGoogleMaps: true,
    showWaze: true,
    dateDayFontSize: 56,
    dateMonthFontSize: 16,
    timeFontSize: 14,
    addressFontSize: 13,
    countdownNumberFontSize: 18,
  },
  {
    name: "זכוכית מודרנית",
    description: "עיצוב זכוכית מודרני עם אפקט טשטוש",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#667eea",
    secondaryColor: "#764ba2",
    cardStyle: CardStyle.GLASS,
    cardBackground: "rgba(255, 255, 255, 0.85)",
    cardBorderRadius: 24,
    cardPadding: 28,
    cardMaxWidth: 448,
    cardBlur: 16,
    textColor: "#1a1a1a",
    accentColor: "#667eea",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showTimeSection: true,
    showAddressSection: true,
    showGoogleMaps: true,
    showWaze: true,
    dateDayFontSize: 56,
    dateMonthFontSize: 16,
    timeFontSize: 14,
    addressFontSize: 13,
    countdownNumberFontSize: 18,
    dateCardBackground: "rgba(255, 255, 255, 0.5)",
    dateCardAccentColor: "#667eea",
  },
  {
    name: "רומנטי ורוד",
    description: "עיצוב רך עם גווני ורוד",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#fce7f3",
    secondaryColor: "#fbcfe8",
    cardStyle: CardStyle.GLASS,
    cardBackground: "#ffffff",
    cardBorderRadius: 24,
    cardPadding: 32,
    cardMaxWidth: 448,
    cardOpacity: 0.95,
    cardBlur: 8,
    textColor: "#831843",
    accentColor: "#db2777",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "אלגנטי זהב",
    description: "עיצוב יוקרתי עם נגיעות זהב",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.COLOR,
    backgroundColor: "#1a1a1a",
    cardStyle: CardStyle.BORDERED,
    cardBackground: "#ffffff",
    cardBorderRadius: 8,
    cardPadding: 32,
    cardMaxWidth: 448,
    textColor: "#1a1a1a",
    primaryColor: "#d4af37",
    accentColor: "#d4af37",
    dateDisplayStyle: DateDisplayStyle.CARD,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "טבע ירוק",
    description: "עיצוב טבעי עם גווני ירוק",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#d1fae5",
    secondaryColor: "#a7f3d0",
    cardStyle: CardStyle.ELEVATED,
    cardBackground: "#ffffff",
    cardBorderRadius: 20,
    cardPadding: 28,
    cardMaxWidth: 448,
    textColor: "#064e3b",
    accentColor: "#059669",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "מודרני מינימליסטי",
    description: "עיצוב נקי ומודרני",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.COLOR,
    backgroundColor: "#ffffff",
    cardStyle: CardStyle.FLAT,
    cardBackground: "#f3f4f6",
    cardBorderRadius: 4,
    cardPadding: 24,
    cardMaxWidth: 400,
    textColor: "#111827",
    primaryColor: "#111827",
    accentColor: "#111827",
    dateDisplayStyle: DateDisplayStyle.MINIMAL,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "שקיעה רומנטית",
    description: "גרדיאנט חם של שקיעה",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#fef3c7",
    secondaryColor: "#fecaca",
    cardStyle: CardStyle.GLASS,
    cardBackground: "#ffffff",
    cardBorderRadius: 16,
    cardPadding: 28,
    cardMaxWidth: 448,
    cardOpacity: 0.9,
    cardBlur: 10,
    textColor: "#78350f",
    accentColor: "#ea580c",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "כחול שלו",
    description: "עיצוב רגוע בגווני כחול",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#dbeafe",
    secondaryColor: "#bfdbfe",
    cardStyle: CardStyle.ELEVATED,
    cardBackground: "#ffffff",
    cardBorderRadius: 16,
    cardPadding: 32,
    cardMaxWidth: 448,
    textColor: "#1e3a8a",
    accentColor: "#2563eb",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
  {
    name: "סגול מלכותי",
    description: "עיצוב מלכותי בגווני סגול",
    isSystem: true,
    advancedMode: false,
    backgroundType: BackgroundType.GRADIENT,
    primaryColor: "#e9d5ff",
    secondaryColor: "#d8b4fe",
    cardStyle: CardStyle.BORDERED,
    cardBackground: "#ffffff",
    cardBorderRadius: 12,
    cardPadding: 28,
    cardMaxWidth: 448,
    textColor: "#581c87",
    accentColor: "#9333ea",
    dateDisplayStyle: DateDisplayStyle.CALENDAR,
    showCountdown: true,
    showGoogleMaps: true,
    showWaze: true,
  },
];

async function main() {
  console.log("Seeding system templates...");

  for (const template of systemTemplates) {
    // Check if template already exists
    const existing = await prisma.rsvpTemplate.findFirst({
      where: {
        name: template.name,
        isSystem: true,
      },
    });

    if (existing) {
      console.log(`Template "${template.name}" already exists, skipping...`);
      continue;
    }

    await prisma.rsvpTemplate.create({
      data: template,
    });
    console.log(`Created template: ${template.name}`);
  }

  console.log("Seeding completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
